name: Oguuk
title: oguuk | A blog theme for Jekyll
description: 오국원님의 github blog 입니다.
tags:
  - blog
  - template
  - jekyll
  - theme
  - github
show_hero: true
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Feed
    url: /stock
  - title: Contact
    url: /contact
email: ogw135@gmail.com
# See: https://disqus.com/
disqus_username: https-oguuk-github-io
# Contact Form Setting
# See: https://formspree.io/
formspree_form_id: xqknkgyw
